import type { PatchNoteLocale } from '@/data/patch-notes/types';

const copy = {
  ko: {
    chromeServices: '← 서비스 목록',
    chromePatchNotes: '패치노트',
    listHeading: '패치노트',
    listIntroSuffix: '의 업데이트 내역입니다.',
    detailMetaPatchNotes: '패치노트',
    tableTitle: '제목',
    tableType: '타입',
    tableCreated: '작성일',
    tableUpdated: '수정일',
    emptyHint: '에 마크다운을 추가해 주세요.',
    emptyNoNotes: '등록된 패치노트가 없습니다.',
    detailEyebrow: '패치노트',
    fieldType: '타입',
    fieldCreated: '작성일',
    fieldUpdated: '수정일',
    backToList: '← 패치노트 목록',
    imageExpandHint: '클릭하여 확대',
    lightboxClose: '닫기',
    lightboxImagePreview: '이미지 미리보기',
    carouselPrev: '이전 이미지',
    carouselNext: '다음 이미지',
    carouselRegion: '이미지 갤러리',
    carouselDots: '슬라이드 선택',
    filterMajorGroupLabel: '메이저 버전 필터',
    filterMajorAll: '전체',
    filterMajorOther: '기타',
    filterMajorEmpty: '선택한 메이저에 해당하는 패치노트가 없습니다.',
  },
  en: {
    chromeServices: '← Services',
    chromePatchNotes: 'Patch notes',
    listHeading: 'Patch notes',
    listIntroSuffix: ' — release history.',
    detailMetaPatchNotes: 'Patch notes',
    tableTitle: 'Title',
    tableType: 'Type',
    tableCreated: 'Created',
    tableUpdated: 'Updated',
    emptyHint: ' and add markdown files.',
    emptyNoNotes: 'No patch notes yet.',
    detailEyebrow: 'Patch notes',
    fieldType: 'Type',
    fieldCreated: 'Created',
    fieldUpdated: 'Updated',
    backToList: '← Patch notes',
    imageExpandHint: 'Click to enlarge',
    lightboxClose: 'Close',
    lightboxImagePreview: 'Image preview',
    carouselPrev: 'Previous image',
    carouselNext: 'Next image',
    carouselRegion: 'Image gallery',
    carouselDots: 'Choose slide',
    filterMajorGroupLabel: 'Filter by major version',
    filterMajorAll: 'All',
    filterMajorOther: 'Other',
    filterMajorEmpty: 'No patch notes for this major version.',
  },
} as const;

export function patchNotesUi(locale: PatchNoteLocale) {
  return copy[locale];
}
